AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 110

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 60
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
